Update release-on-github.yaml

diff --git a/.github/workflows/release-on-github.yaml b/.github/workflows/release-on-github.yaml
--- a/.github/workflows/release-on-github.yaml
+++ b/.github/workflows/release-on-github.yaml
@@ -1,6 +1,6 @@
 name: Release - SwaggerHub CLI on GitHub
 on:
-  # This will be trigger if the PR label == gen_release 
+  # This will be trigger if the PR label == gen_release
   pull_request:
     types:
       - labeled
@@ -22,25 +22,35 @@ jobs:
           git fetch --prune --tags
           git tag --list
         id: fetch_tags
-        
+
       # npm install changelog
       - name: run_npm_install_changelog
         run: sudo npm i generate-changelog -g
         id: run_npm_install_changelog
 
-      # Get current tag and release tag
+      # Get current tag and release tag.
+      # Release tag comes from package.json.
+      # Current tag is the tag prior to release tag.
       - name: generate_tag_vars
-        run: | 
+        run: |
           version_tag_release="v$(cat package.json | jq --raw-output .version)"
-          version_tag_current="git describe --abbrev=0 --tags ${version_tag_release}^" # This gets the tag(accross all branches) prior to version_tag_release via '^'
+          version_tag_current="git describe --abbrev=0 --tags ${version_tag_release}^"
           echo "::set-output name=version_tag_release::$version_tag_release"
           echo "::set-output name=version_tag_current::$version_tag_current"
           echo "Current:${version_tag_current} / Release:${version_tag_release}"
 
-      # Generate a changelog from a tag range, parse and set as outputs.
+      # Basic check to find the new release tag, exit if not found.
+      - name: verify_release_tag_exists
+        run: |
+          git tag --list > /tmp/tag_lst
+          if ! grep ${{ steps.generate_tag_vars.outputs.version_tag_release }} /tmp/tag_lst; then
+            echo "Unable to find tag ${{ steps.generate_tag_vars.outputs.version_tag_release }} from 'git tags'"
+            exit; fi
+
+      # Generate a changelog from a tag range, parse and set as an output.
       # Prior changelog method: changelog="$(generate-changelog --tag ${{ github.event.pull_request.body }} $* --file -)"
       - name: generate_tag_range_changelog
-        run: | 
+        run: |
           changelog="$(generate-changelog --tag ${{ steps.generate_tag_vars.outputs.version_tag_current }}..${{ steps.generate_tag_vars.outputs.version_tag_release }} $* --file -)"
           changelog="${changelog//'%'/'%25'}"
           changelog="${changelog//$'\n'/'%0A'}"
@@ -59,5 +69,5 @@ jobs:
           release_name: SwaggerHub CLI Release ${{ steps.generate_tag_vars.outputs.version_tag_release }}
           body: |
             ${{ steps.generate_tag_range_changelog.outputs.changelog }}
-          draft: true # Allow swaggerhub-cli team approve the release notes before making public. 
+          draft: true # Allow swaggerhub-cli team approve the release notes before making public.
           prerelease: false
